<!--?xml version="1.0" encoding="UTF-8"?-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtmll/DTD/xhtmll-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta charset="UTF-8">
  <title>1099 Tax Form</title>
  <style type="text/css">
    h1 {
      font-size: 32pt;
    }
  </style>
</head>
<body>
  <h1>TODO</h1>
</body>
</html>